# ref: https://github.com/docker-library/official-images
name: amd64 Docker

on:
  push:
  pull_request:

jobs:
  bazel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #platform: [amd64, arm64, riscv64]
        platform: [amd64]
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
      fail-fast: false
    env:
      PLATFORM: ${{ matrix.platform }}
      DISTRO: ${{ matrix.distro }}
    steps:
    - uses: actions/checkout@v2
    - name: Check docker
      run: |
        docker info
        docker buildx ls
    - name: Build env image
      run: make --directory=ci ${PLATFORM}_${DISTRO}_env
    - name: Build devel project
      run: make --directory=ci ${PLATFORM}_${DISTRO}_devel
    - name: Build project
      run: make --directory=ci ${PLATFORM}_${DISTRO}_build
    - name: Test project
      run: make --directory=ci ${PLATFORM}_${DISTRO}_test
