# ref: https://github.com/actions/runner-images
name: amd64 Windows CMake

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  visual-studio:
    # ref: https://github.com/actions/runner-images
    strategy:
      matrix:
        runner: [windows-2022, windows-2019]
      fail-fast: false # Don't cancel all jobs if one fails.
    runs-on: ${{ matrix.runner }}
    #runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check cmake
        run: |
          cmake --version
          cmake -G || true
      - name: Configure
        run: >
          cmake
          -S.
          -Bbuild
          -DCMAKE_CONFIGURATION_TYPES=Release
          -DCMAKE_INSTALL_PREFIX=install
      - name: Build
        run: >
          cmake
          --build build
          --config Release
          --target ALL_BUILD
          -v
      - name: Test
        run: >
          cmake
          --build build
          --config Release
          --target RUN_TESTS
          -v
      - name: Install
        run: >
          cmake
          --build build
          --config Release
          --target INSTALL
          -v
