# ref: https://github.com/actions/runner-images
name: amd64 Linux Bazel

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
          #'3.8',
          #'3.9',
          #'3.10',
          '3.11'
        ]
        option: [
          #'',
          #'--repo_env=BAZEL_CXXOPTS="-std=c++17"',
          #'--action_env=BAZEL_CXXOPTS="-std=c++17"',
          '--cxxopt="-std=c++17"'
        ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install Bazel
        run: |
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt-get update
          sudo apt-get install bazel
      - name: Check bazel
        run:  bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          ${{ matrix.option }}
          --subcommands=true
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          ${{ matrix.option }}
          --test_output=all
          ...
