name: amd64 macOS

on:
  push:
  pull_request:

jobs:
  bazel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bazel
      run: |
        brew update
        #brew install bazel
    - name: Check Bazel
      run: bazel version
    - name: Build
      run: bazel build --cxxopt=-std=c++17 //...:all
    - name: Test
      run: bazel test --test_output=errors --cxxopt=-std=c++17 //...:all
